#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("YoutubePlayerApiQs.Resource", IsApplication=true)]

namespace YoutubePlayerApiQs
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int constraintSet = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int layout_constraintBaseline_creator = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int layout_constraintBaseline_toBaselineOf = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int layout_constraintBottom_creator = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int layout_constraintBottom_toBottomOf = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int layout_constraintBottom_toTopOf = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int layout_constraintDimensionRatio = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int layout_constraintEnd_toEndOf = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int layout_constraintEnd_toStartOf = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int layout_constraintGuide_begin = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int layout_constraintGuide_end = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int layout_constraintGuide_percent = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int layout_constraintHeight_default = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int layout_constraintHeight_max = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int layout_constraintHeight_min = 2130771982;
			
			// aapt resource value: 0x7f01000f
			public const int layout_constraintHorizontal_bias = 2130771983;
			
			// aapt resource value: 0x7f010010
			public const int layout_constraintHorizontal_chainStyle = 2130771984;
			
			// aapt resource value: 0x7f010011
			public const int layout_constraintHorizontal_weight = 2130771985;
			
			// aapt resource value: 0x7f010012
			public const int layout_constraintLeft_creator = 2130771986;
			
			// aapt resource value: 0x7f010013
			public const int layout_constraintLeft_toLeftOf = 2130771987;
			
			// aapt resource value: 0x7f010014
			public const int layout_constraintLeft_toRightOf = 2130771988;
			
			// aapt resource value: 0x7f010015
			public const int layout_constraintRight_creator = 2130771989;
			
			// aapt resource value: 0x7f010016
			public const int layout_constraintRight_toLeftOf = 2130771990;
			
			// aapt resource value: 0x7f010017
			public const int layout_constraintRight_toRightOf = 2130771991;
			
			// aapt resource value: 0x7f010018
			public const int layout_constraintStart_toEndOf = 2130771992;
			
			// aapt resource value: 0x7f010019
			public const int layout_constraintStart_toStartOf = 2130771993;
			
			// aapt resource value: 0x7f01001a
			public const int layout_constraintTop_creator = 2130771994;
			
			// aapt resource value: 0x7f01001b
			public const int layout_constraintTop_toBottomOf = 2130771995;
			
			// aapt resource value: 0x7f01001c
			public const int layout_constraintTop_toTopOf = 2130771996;
			
			// aapt resource value: 0x7f01001d
			public const int layout_constraintVertical_bias = 2130771997;
			
			// aapt resource value: 0x7f01001e
			public const int layout_constraintVertical_chainStyle = 2130771998;
			
			// aapt resource value: 0x7f01001f
			public const int layout_constraintVertical_weight = 2130771999;
			
			// aapt resource value: 0x7f010020
			public const int layout_constraintWidth_default = 2130772000;
			
			// aapt resource value: 0x7f010021
			public const int layout_constraintWidth_max = 2130772001;
			
			// aapt resource value: 0x7f010022
			public const int layout_constraintWidth_min = 2130772002;
			
			// aapt resource value: 0x7f010023
			public const int layout_editor_absoluteX = 2130772003;
			
			// aapt resource value: 0x7f010024
			public const int layout_editor_absoluteY = 2130772004;
			
			// aapt resource value: 0x7f010025
			public const int layout_goneMarginBottom = 2130772005;
			
			// aapt resource value: 0x7f010026
			public const int layout_goneMarginEnd = 2130772006;
			
			// aapt resource value: 0x7f010027
			public const int layout_goneMarginLeft = 2130772007;
			
			// aapt resource value: 0x7f010028
			public const int layout_goneMarginRight = 2130772008;
			
			// aapt resource value: 0x7f010029
			public const int layout_goneMarginStart = 2130772009;
			
			// aapt resource value: 0x7f01002a
			public const int layout_goneMarginTop = 2130772010;
			
			// aapt resource value: 0x7f01002b
			public const int layout_optimizationLevel = 2130772011;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int gray = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int loading_thumbnail = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int no_thumbnail = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050006
			public const int all = 2131034118;
			
			// aapt resource value: 0x7f05002f
			public const int autoplay_checkbox = 2131034159;
			
			// aapt resource value: 0x7f050007
			public const int basic = 2131034119;
			
			// aapt resource value: 0x7f050011
			public const int btn_custom_fullscreen_handling = 2131034129;
			
			// aapt resource value: 0x7f050010
			public const int btn_custom_player_control = 2131034128;
			
			// aapt resource value: 0x7f05000f
			public const int btn_simple_playerfragment = 2131034127;
			
			// aapt resource value: 0x7f05000e
			public const int btn_simple_playerview = 2131034126;
			
			// aapt resource value: 0x7f050012
			public const int btn_standalone_player = 2131034130;
			
			// aapt resource value: 0x7f05000d
			public const int btn_video_list = 2131034125;
			
			// aapt resource value: 0x7f050014
			public const int btn_video_wall = 2131034132;
			
			// aapt resource value: 0x7f050013
			public const int btn_youtube_launcher_intent = 2131034131;
			
			// aapt resource value: 0x7f050008
			public const int chains = 2131034120;
			
			// aapt resource value: 0x7f050034
			public const int close_button = 2131034164;
			
			// aapt resource value: 0x7f050031
			public const int container = 2131034161;
			
			// aapt resource value: 0x7f050029
			public const int event_log = 2131034153;
			
			// aapt resource value: 0x7f05001a
			public const int fullscreen_button = 2131034138;
			
			// aapt resource value: 0x7f05001b
			public const int intent_list = 2131034139;
			
			// aapt resource value: 0x7f050019
			public const int landscape_fullscreen_checkbox = 2131034137;
			
			// aapt resource value: 0x7f050016
			public const int layout = 2131034134;
			
			// aapt resource value: 0x7f050030
			public const int lightbox_checkbox = 2131034160;
			
			// aapt resource value: 0x7f050032
			public const int list_fragment = 2131034162;
			
			// aapt resource value: 0x7f05001e
			public const int list_item_disabled_text = 2131034142;
			
			// aapt resource value: 0x7f05001d
			public const int list_item_text = 2131034141;
			
			// aapt resource value: 0x7f050009
			public const int none = 2131034121;
			
			// aapt resource value: 0x7f050018
			public const int other_views = 2131034136;
			
			// aapt resource value: 0x7f050004
			public const int packed = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int parent = 2131034113;
			
			// aapt resource value: 0x7f050021
			public const int pause_button = 2131034145;
			
			// aapt resource value: 0x7f050020
			public const int play_button = 2131034144;
			
			// aapt resource value: 0x7f050017
			public const int player = 2131034135;
			
			// aapt resource value: 0x7f05000b
			public const int player_fragment = 2131034123;
			
			// aapt resource value: 0x7f050000
			public const int player_view = 2131034112;
			
			// aapt resource value: 0x7f050022
			public const int skip_to_text = 2131034146;
			
			// aapt resource value: 0x7f050002
			public const int spread = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int spread_inside = 2131034117;
			
			// aapt resource value: 0x7f05002d
			public const int start_index_text = 2131034157;
			
			// aapt resource value: 0x7f05002b
			public const int start_playlist_button = 2131034155;
			
			// aapt resource value: 0x7f05002e
			public const int start_time_text = 2131034158;
			
			// aapt resource value: 0x7f05002a
			public const int start_video_button = 2131034154;
			
			// aapt resource value: 0x7f05002c
			public const int start_video_list_button = 2131034156;
			
			// aapt resource value: 0x7f050023
			public const int state_text = 2131034147;
			
			// aapt resource value: 0x7f050028
			public const int style_chromeless = 2131034152;
			
			// aapt resource value: 0x7f050026
			public const int style_default = 2131034150;
			
			// aapt resource value: 0x7f050027
			public const int style_minimal = 2131034151;
			
			// aapt resource value: 0x7f050025
			public const int style_radio_group = 2131034149;
			
			// aapt resource value: 0x7f050037
			public const int text = 2131034167;
			
			// aapt resource value: 0x7f050036
			public const int thumbnail = 2131034166;
			
			// aapt resource value: 0x7f05000c
			public const int tutorial_text = 2131034124;
			
			// aapt resource value: 0x7f050033
			public const int video_box = 2131034163;
			
			// aapt resource value: 0x7f05001f
			public const int video_chooser = 2131034143;
			
			// aapt resource value: 0x7f050035
			public const int video_fragment_container = 2131034165;
			
			// aapt resource value: 0x7f05000a
			public const int view_container = 2131034122;
			
			// aapt resource value: 0x7f050003
			public const int wrap = 2131034115;
			
			// aapt resource value: 0x7f050015
			public const int youtube_fragment = 2131034133;
			
			// aapt resource value: 0x7f05001c
			public const int youtube_version_text = 2131034140;
			
			// aapt resource value: 0x7f050024
			public const int youtube_view = 2131034148;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int action_bar_demo = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int demo_home = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int fragments_demo = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int fullscreen_demo = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int intents_demo = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int list_item = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int player_controls_container = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int player_controls_demo = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int playerview_demo = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int standalone_player_demo = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int video_list_demo = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int video_list_item = 2130903051;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f06000b
			public const int action_bar_demo_name = 2131099659;
			
			// aapt resource value: 0x7f060029
			public const int actionbar_tutorial = 2131099689;
			
			// aapt resource value: 0x7f060004
			public const int app_name = 2131099652;
			
			// aapt resource value: 0x7f060020
			public const int autoplay = 2131099680;
			
			// aapt resource value: 0x7f06001a
			public const int chromeless = 2131099674;
			
			// aapt resource value: 0x7f060018
			public const int def = 2131099672;
			
			// aapt resource value: 0x7f060010
			public const int demo_select = 2131099664;
			
			// aapt resource value: 0x7f060027
			public const int enter_fullscreen = 2131099687;
			
			// aapt resource value: 0x7f06002b
			public const int error_player = 2131099691;
			
			// aapt resource value: 0x7f06002a
			public const int error_thumbnail_view = 2131099690;
			
			// aapt resource value: 0x7f060009
			public const int fragment_demo_name = 2131099657;
			
			// aapt resource value: 0x7f06000c
			public const int fullscreen_demo_name = 2131099660;
			
			// aapt resource value: 0x7f060026
			public const int fullscreen_tutorial = 2131099686;
			
			// aapt resource value: 0x7f060023
			public const int intent_disabled = 2131099683;
			
			// aapt resource value: 0x7f060022
			public const int intent_select = 2131099682;
			
			// aapt resource value: 0x7f06000d
			public const int intents_demo_name = 2131099661;
			
			// aapt resource value: 0x7f060001
			public const int isLaunchableActivity = 2131099649;
			
			// aapt resource value: 0x7f060028
			public const int landscape_fullscreen = 2131099688;
			
			// aapt resource value: 0x7f060021
			public const int lightbox_mode = 2131099681;
			
			// aapt resource value: 0x7f060012
			public const int list_item_disabled = 2131099666;
			
			// aapt resource value: 0x7f060002
			public const int loggingTag = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int minVersion = 2131099648;
			
			// aapt resource value: 0x7f060019
			public const int minimal = 2131099673;
			
			// aapt resource value: 0x7f060014
			public const int pause = 2131099668;
			
			// aapt resource value: 0x7f060013
			public const int play = 2131099667;
			
			// aapt resource value: 0x7f06001c
			public const int play_playlist = 2131099676;
			
			// aapt resource value: 0x7f06001b
			public const int play_video = 2131099675;
			
			// aapt resource value: 0x7f06001d
			public const int play_video_list = 2131099677;
			
			// aapt resource value: 0x7f06000a
			public const int player_controls_demo_name = 2131099658;
			
			// aapt resource value: 0x7f060017
			public const int player_style = 2131099671;
			
			// aapt resource value: 0x7f06000f
			public const int playerfragment_text = 2131099663;
			
			// aapt resource value: 0x7f060008
			public const int playerview_demo_name = 2131099656;
			
			// aapt resource value: 0x7f06000e
			public const int playerview_text = 2131099662;
			
			// aapt resource value: 0x7f060016
			public const int seconds = 2131099670;
			
			// aapt resource value: 0x7f060015
			public const int skip_to = 2131099669;
			
			// aapt resource value: 0x7f060011
			public const int some_demos_disabled = 2131099665;
			
			// aapt resource value: 0x7f060007
			public const int standalone_player_demo_name = 2131099655;
			
			// aapt resource value: 0x7f06001e
			public const int start_index = 2131099678;
			
			// aapt resource value: 0x7f06001f
			public const int start_time = 2131099679;
			
			// aapt resource value: 0x7f060006
			public const int videolist_demo_name = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int videowall_demo_name = 2131099653;
			
			// aapt resource value: 0x7f060003
			public const int youtube_api_demo = 2131099651;
			
			// aapt resource value: 0x7f060024
			public const int youtube_currently_installed = 2131099684;
			
			// aapt resource value: 0x7f060025
			public const int youtube_not_installed = 2131099685;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int AppTheme = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int BlackNoBarsTheme = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int BlackNoTitleBarTheme = 2131165186;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ConstraintLayout_Layout = new int[] {
					16842948,
					16843039,
					16843040,
					16843071,
					16843072,
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002,
					2130772003,
					2130772004,
					2130772005,
					2130772006,
					2130772007,
					2130772008,
					2130772009,
					2130772010,
					2130772011};
			
			// aapt resource value: 2
			public const int ConstraintLayout_Layout_android_maxHeight = 2;
			
			// aapt resource value: 1
			public const int ConstraintLayout_Layout_android_maxWidth = 1;
			
			// aapt resource value: 4
			public const int ConstraintLayout_Layout_android_minHeight = 4;
			
			// aapt resource value: 3
			public const int ConstraintLayout_Layout_android_minWidth = 3;
			
			// aapt resource value: 0
			public const int ConstraintLayout_Layout_android_orientation = 0;
			
			// aapt resource value: 5
			public const int ConstraintLayout_Layout_constraintSet = 5;
			
			// aapt resource value: 6
			public const int ConstraintLayout_Layout_layout_constraintBaseline_creator = 6;
			
			// aapt resource value: 7
			public const int ConstraintLayout_Layout_layout_constraintBaseline_toBaselineOf = 7;
			
			// aapt resource value: 8
			public const int ConstraintLayout_Layout_layout_constraintBottom_creator = 8;
			
			// aapt resource value: 9
			public const int ConstraintLayout_Layout_layout_constraintBottom_toBottomOf = 9;
			
			// aapt resource value: 10
			public const int ConstraintLayout_Layout_layout_constraintBottom_toTopOf = 10;
			
			// aapt resource value: 11
			public const int ConstraintLayout_Layout_layout_constraintDimensionRatio = 11;
			
			// aapt resource value: 12
			public const int ConstraintLayout_Layout_layout_constraintEnd_toEndOf = 12;
			
			// aapt resource value: 13
			public const int ConstraintLayout_Layout_layout_constraintEnd_toStartOf = 13;
			
			// aapt resource value: 14
			public const int ConstraintLayout_Layout_layout_constraintGuide_begin = 14;
			
			// aapt resource value: 15
			public const int ConstraintLayout_Layout_layout_constraintGuide_end = 15;
			
			// aapt resource value: 16
			public const int ConstraintLayout_Layout_layout_constraintGuide_percent = 16;
			
			// aapt resource value: 17
			public const int ConstraintLayout_Layout_layout_constraintHeight_default = 17;
			
			// aapt resource value: 18
			public const int ConstraintLayout_Layout_layout_constraintHeight_max = 18;
			
			// aapt resource value: 19
			public const int ConstraintLayout_Layout_layout_constraintHeight_min = 19;
			
			// aapt resource value: 20
			public const int ConstraintLayout_Layout_layout_constraintHorizontal_bias = 20;
			
			// aapt resource value: 21
			public const int ConstraintLayout_Layout_layout_constraintHorizontal_chainStyle = 21;
			
			// aapt resource value: 22
			public const int ConstraintLayout_Layout_layout_constraintHorizontal_weight = 22;
			
			// aapt resource value: 23
			public const int ConstraintLayout_Layout_layout_constraintLeft_creator = 23;
			
			// aapt resource value: 24
			public const int ConstraintLayout_Layout_layout_constraintLeft_toLeftOf = 24;
			
			// aapt resource value: 25
			public const int ConstraintLayout_Layout_layout_constraintLeft_toRightOf = 25;
			
			// aapt resource value: 26
			public const int ConstraintLayout_Layout_layout_constraintRight_creator = 26;
			
			// aapt resource value: 27
			public const int ConstraintLayout_Layout_layout_constraintRight_toLeftOf = 27;
			
			// aapt resource value: 28
			public const int ConstraintLayout_Layout_layout_constraintRight_toRightOf = 28;
			
			// aapt resource value: 29
			public const int ConstraintLayout_Layout_layout_constraintStart_toEndOf = 29;
			
			// aapt resource value: 30
			public const int ConstraintLayout_Layout_layout_constraintStart_toStartOf = 30;
			
			// aapt resource value: 31
			public const int ConstraintLayout_Layout_layout_constraintTop_creator = 31;
			
			// aapt resource value: 32
			public const int ConstraintLayout_Layout_layout_constraintTop_toBottomOf = 32;
			
			// aapt resource value: 33
			public const int ConstraintLayout_Layout_layout_constraintTop_toTopOf = 33;
			
			// aapt resource value: 34
			public const int ConstraintLayout_Layout_layout_constraintVertical_bias = 34;
			
			// aapt resource value: 35
			public const int ConstraintLayout_Layout_layout_constraintVertical_chainStyle = 35;
			
			// aapt resource value: 36
			public const int ConstraintLayout_Layout_layout_constraintVertical_weight = 36;
			
			// aapt resource value: 37
			public const int ConstraintLayout_Layout_layout_constraintWidth_default = 37;
			
			// aapt resource value: 38
			public const int ConstraintLayout_Layout_layout_constraintWidth_max = 38;
			
			// aapt resource value: 39
			public const int ConstraintLayout_Layout_layout_constraintWidth_min = 39;
			
			// aapt resource value: 40
			public const int ConstraintLayout_Layout_layout_editor_absoluteX = 40;
			
			// aapt resource value: 41
			public const int ConstraintLayout_Layout_layout_editor_absoluteY = 41;
			
			// aapt resource value: 42
			public const int ConstraintLayout_Layout_layout_goneMarginBottom = 42;
			
			// aapt resource value: 43
			public const int ConstraintLayout_Layout_layout_goneMarginEnd = 43;
			
			// aapt resource value: 44
			public const int ConstraintLayout_Layout_layout_goneMarginLeft = 44;
			
			// aapt resource value: 45
			public const int ConstraintLayout_Layout_layout_goneMarginRight = 45;
			
			// aapt resource value: 46
			public const int ConstraintLayout_Layout_layout_goneMarginStart = 46;
			
			// aapt resource value: 47
			public const int ConstraintLayout_Layout_layout_goneMarginTop = 47;
			
			// aapt resource value: 48
			public const int ConstraintLayout_Layout_layout_optimizationLevel = 48;
			
			public static int[] ConstraintSet = new int[] {
					16842948,
					16842960,
					16842972,
					16842996,
					16842997,
					16842999,
					16843000,
					16843001,
					16843002,
					16843551,
					16843552,
					16843553,
					16843554,
					16843555,
					16843556,
					16843557,
					16843559,
					16843560,
					16843701,
					16843702,
					16843770,
					16843840,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002,
					2130772003,
					2130772004,
					2130772005,
					2130772006,
					2130772007,
					2130772008,
					2130772009,
					2130772010};
			
			// aapt resource value: 9
			public const int ConstraintSet_android_alpha = 9;
			
			// aapt resource value: 21
			public const int ConstraintSet_android_elevation = 21;
			
			// aapt resource value: 1
			public const int ConstraintSet_android_id = 1;
			
			// aapt resource value: 4
			public const int ConstraintSet_android_layout_height = 4;
			
			// aapt resource value: 8
			public const int ConstraintSet_android_layout_marginBottom = 8;
			
			// aapt resource value: 19
			public const int ConstraintSet_android_layout_marginEnd = 19;
			
			// aapt resource value: 5
			public const int ConstraintSet_android_layout_marginLeft = 5;
			
			// aapt resource value: 7
			public const int ConstraintSet_android_layout_marginRight = 7;
			
			// aapt resource value: 18
			public const int ConstraintSet_android_layout_marginStart = 18;
			
			// aapt resource value: 6
			public const int ConstraintSet_android_layout_marginTop = 6;
			
			// aapt resource value: 3
			public const int ConstraintSet_android_layout_width = 3;
			
			// aapt resource value: 0
			public const int ConstraintSet_android_orientation = 0;
			
			// aapt resource value: 16
			public const int ConstraintSet_android_rotationX = 16;
			
			// aapt resource value: 17
			public const int ConstraintSet_android_rotationY = 17;
			
			// aapt resource value: 14
			public const int ConstraintSet_android_scaleX = 14;
			
			// aapt resource value: 15
			public const int ConstraintSet_android_scaleY = 15;
			
			// aapt resource value: 10
			public const int ConstraintSet_android_transformPivotX = 10;
			
			// aapt resource value: 11
			public const int ConstraintSet_android_transformPivotY = 11;
			
			// aapt resource value: 12
			public const int ConstraintSet_android_translationX = 12;
			
			// aapt resource value: 13
			public const int ConstraintSet_android_translationY = 13;
			
			// aapt resource value: 20
			public const int ConstraintSet_android_translationZ = 20;
			
			// aapt resource value: 2
			public const int ConstraintSet_android_visibility = 2;
			
			// aapt resource value: 22
			public const int ConstraintSet_layout_constraintBaseline_creator = 22;
			
			// aapt resource value: 23
			public const int ConstraintSet_layout_constraintBaseline_toBaselineOf = 23;
			
			// aapt resource value: 24
			public const int ConstraintSet_layout_constraintBottom_creator = 24;
			
			// aapt resource value: 25
			public const int ConstraintSet_layout_constraintBottom_toBottomOf = 25;
			
			// aapt resource value: 26
			public const int ConstraintSet_layout_constraintBottom_toTopOf = 26;
			
			// aapt resource value: 27
			public const int ConstraintSet_layout_constraintDimensionRatio = 27;
			
			// aapt resource value: 28
			public const int ConstraintSet_layout_constraintEnd_toEndOf = 28;
			
			// aapt resource value: 29
			public const int ConstraintSet_layout_constraintEnd_toStartOf = 29;
			
			// aapt resource value: 30
			public const int ConstraintSet_layout_constraintGuide_begin = 30;
			
			// aapt resource value: 31
			public const int ConstraintSet_layout_constraintGuide_end = 31;
			
			// aapt resource value: 32
			public const int ConstraintSet_layout_constraintGuide_percent = 32;
			
			// aapt resource value: 33
			public const int ConstraintSet_layout_constraintHeight_default = 33;
			
			// aapt resource value: 34
			public const int ConstraintSet_layout_constraintHeight_max = 34;
			
			// aapt resource value: 35
			public const int ConstraintSet_layout_constraintHeight_min = 35;
			
			// aapt resource value: 36
			public const int ConstraintSet_layout_constraintHorizontal_bias = 36;
			
			// aapt resource value: 37
			public const int ConstraintSet_layout_constraintHorizontal_chainStyle = 37;
			
			// aapt resource value: 38
			public const int ConstraintSet_layout_constraintHorizontal_weight = 38;
			
			// aapt resource value: 39
			public const int ConstraintSet_layout_constraintLeft_creator = 39;
			
			// aapt resource value: 40
			public const int ConstraintSet_layout_constraintLeft_toLeftOf = 40;
			
			// aapt resource value: 41
			public const int ConstraintSet_layout_constraintLeft_toRightOf = 41;
			
			// aapt resource value: 42
			public const int ConstraintSet_layout_constraintRight_creator = 42;
			
			// aapt resource value: 43
			public const int ConstraintSet_layout_constraintRight_toLeftOf = 43;
			
			// aapt resource value: 44
			public const int ConstraintSet_layout_constraintRight_toRightOf = 44;
			
			// aapt resource value: 45
			public const int ConstraintSet_layout_constraintStart_toEndOf = 45;
			
			// aapt resource value: 46
			public const int ConstraintSet_layout_constraintStart_toStartOf = 46;
			
			// aapt resource value: 47
			public const int ConstraintSet_layout_constraintTop_creator = 47;
			
			// aapt resource value: 48
			public const int ConstraintSet_layout_constraintTop_toBottomOf = 48;
			
			// aapt resource value: 49
			public const int ConstraintSet_layout_constraintTop_toTopOf = 49;
			
			// aapt resource value: 50
			public const int ConstraintSet_layout_constraintVertical_bias = 50;
			
			// aapt resource value: 51
			public const int ConstraintSet_layout_constraintVertical_chainStyle = 51;
			
			// aapt resource value: 52
			public const int ConstraintSet_layout_constraintVertical_weight = 52;
			
			// aapt resource value: 53
			public const int ConstraintSet_layout_constraintWidth_default = 53;
			
			// aapt resource value: 54
			public const int ConstraintSet_layout_constraintWidth_max = 54;
			
			// aapt resource value: 55
			public const int ConstraintSet_layout_constraintWidth_min = 55;
			
			// aapt resource value: 56
			public const int ConstraintSet_layout_editor_absoluteX = 56;
			
			// aapt resource value: 57
			public const int ConstraintSet_layout_editor_absoluteY = 57;
			
			// aapt resource value: 58
			public const int ConstraintSet_layout_goneMarginBottom = 58;
			
			// aapt resource value: 59
			public const int ConstraintSet_layout_goneMarginEnd = 59;
			
			// aapt resource value: 60
			public const int ConstraintSet_layout_goneMarginLeft = 60;
			
			// aapt resource value: 61
			public const int ConstraintSet_layout_goneMarginRight = 61;
			
			// aapt resource value: 62
			public const int ConstraintSet_layout_goneMarginStart = 62;
			
			// aapt resource value: 63
			public const int ConstraintSet_layout_goneMarginTop = 63;
			
			public static int[] LinearConstraintLayout = new int[] {
					16842948};
			
			// aapt resource value: 0
			public const int LinearConstraintLayout_android_orientation = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
